steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - -c
      - |
        docker build -t XXXXXX-docker.pkg.dev/project/image-registry/image-name -f dockerfile.prod --platform=linux/amd64 --build-arg ORDER_MS_DATABASE_URL=$$DATABASE_URL .
    secretEnv: ['DATABASE_URL']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'XXXXXX-docker.pkg.dev/project/image-registry/image-name']

availableSecrets:
  secretManager:
    - versionName: projects/367390259998/secrets/orders_database_url/versions/1
      env: 'DATABASE_URL'
