services:
  ordes-db:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 6432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123$
      - POSTGRES_DB=orders
